# Generated by Django 5.2 on 2025-04-30 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vente', 'Vente'), ('stock', 'Stock'), ('reapprovisionnement', 'Réapprovisionnement')], max_length=20)),
                ('date_generation', models.DateField()),
                ('resume', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('termine', 'Terminé')], default='en_attente', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('employe', 'Employé')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente')], max_length=10)),
                ('date', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_cours', 'En Cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], max_length=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.utilisateur')),
            ],
        ),
    ]
