# Generated by Django 5.2 on 2025-06-03 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_alter_commande_date_alter_commande_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.PositiveIntegerField(),
        ),
    ]
