# Generated by Django 5.2 on 2025-06-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_produit_date_ajout_alter_produit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='seuil_max',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_min',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
