# Generated by Django 5.2 on 2025-06-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_produit_seuil_max_produit_seuil_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='vendeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
